version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: laravel_app_simple
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - ./laravel-app:/var/www
    networks:
      - laravel
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000
  db:
    image: mysql:8.0
    container_name: mysql_db_simple
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
volumes:
  dbdata:
